#!/bin/bash
echo "Bash Version: ${BASH_VERSION}"


starting_pow=4
final_pow=7
echo '(Bash) Starting tests from %starting_pow upto $final_pow'
echo 

for ((i=starting_pow; i<=final_pow; i++)); do
for ((j= 1; j<10; j++)); do
echo "Testing with $j * 10^$i.."
echo "(Bash) Starting time test"
python3 TestScript.py $j $i plotting
echo
done
done
echo "(Bash) Done!"
									