#!/bin/bash
echo "Bash Version: ${BASH_VERSION}"


starting_pow=4
final_pow=7
final_base=3
echo '(Bash) Starting tests from $starting_pow upto $final_pow'
echo 

for ((i=starting_pow; i<=final_pow; i++)); do

echo "(Bash) Starting time test"
if((i == final_pow))
then
echo "(Bash) final itr"
python3 -m cProfile -o ./TimeProfiles/tenpw$i.prof SingleTest.py 1 $i
mprof run SingleTest.py 1 $i
echo "final_base"
python3 -m cProfile -o ./TimeProfiles/8tenpw$i.prof SingleTest.py $final_base $i
mprof run SingleTest.py $final_base $i
else
echo "(Bash) Testing with 10^$i.."
python3 -m cProfile -o ./TimeProfiles/tenpw$i.prof SingleTest.py 1 $i
echo "(Bash) Starting memory test"
mprof run SingleTest.py 1 $i
echo
fi
done
echo "(Bash) Done!"
